# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a366c7e47fe32e0e5632f664cd5f1eab"
name = "checkout-2"
handle = "checkout-391"
application_url = "https://integral-excellence-photographer-arranged.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "itgdev.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://integral-excellence-photographer-arranged.trycloudflare.com/auth/callback",
  "https://integral-excellence-photographer-arranged.trycloudflare.com/auth/shopify/callback",
  "https://integral-excellence-photographer-arranged.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
